CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    CREATE TABLE IF NOT EXISTS "Files" (
        "Hash" text NOT NULL,
        "Score" integer NOT NULL,
        "FileName" text,
        "SizeBytes" bigint NOT NULL,
        "DetectedType" text,
        "AddDateTime" timestamp with time zone NOT NULL,
        "LastScanned" timestamp with time zone NOT NULL,
        "TimesScanned" integer NOT NULL,
        CONSTRAINT "PK_Files" PRIMARY KEY ("Hash")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    CREATE TABLE IF NOT EXISTS "Scans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FileName" text NOT NULL,
        "Score" real NOT NULL,
        "IsThreat" boolean NOT NULL,
        "ScanTimeMs" integer NOT NULL,
        "ScanDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Scans" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250809182937_InitFilesDb', '9.0.10');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027152153_AddChunks') THEN
    CREATE TABLE IF NOT EXISTS "ChunkUploadSessions" (
        "SessionId" text NOT NULL,
        "FileName" text NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "FileHash" text NOT NULL,
        "TotalChunks" integer NOT NULL,
        "UploadedChunks" boolean[] NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ClientIpAddress" text NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_ChunkUploadSessions" PRIMARY KEY ("SessionId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027152153_AddChunks') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251027152153_AddChunks', '9.0.10');
    END IF;
END $$;
COMMIT;

