CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    CREATE TABLE "Files" (
        "Hash" text NOT NULL,
        "Score" integer NOT NULL,
        "FileName" text,
        "SizeBytes" bigint NOT NULL,
        "DetectedType" text,
        "AddDateTime" timestamp with time zone NOT NULL,
        "LastScanned" timestamp with time zone NOT NULL,
        "TimesScanned" integer NOT NULL,
        CONSTRAINT "PK_Files" PRIMARY KEY ("Hash")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    CREATE TABLE "Scans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FileName" text NOT NULL,
        "Score" real NOT NULL,
        "IsThreat" boolean NOT NULL,
        "ScanTimeMs" integer NOT NULL,
        "ScanDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Scans" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250809182937_InitFilesDb', '9.0.8');
    END IF;
END $$;
COMMIT;

