CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    CREATE TABLE IF NOT EXISTS "Files" (
        "Hash" text NOT NULL,
        "Score" integer NOT NULL,
        "FileName" text,
        "SizeBytes" bigint NOT NULL,
        "DetectedType" text,
        "AddDateTime" timestamp with time zone NOT NULL,
        "LastScanned" timestamp with time zone NOT NULL,
        "TimesScanned" integer NOT NULL,
        CONSTRAINT "PK_Files" PRIMARY KEY ("Hash")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    CREATE TABLE IF NOT EXISTS "Scans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FileName" text NOT NULL,
        "Score" real NOT NULL,
        "IsThreat" boolean NOT NULL,
        "ScanTimeMs" integer NOT NULL,
        "ScanDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Scans" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250809182937_InitFilesDb') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250809182937_InitFilesDb', '10.0.1');
    END IF;
END $$;
COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027152153_AddChunks') THEN
    CREATE TABLE IF NOT EXISTS "ChunkUploadSessions" (
        "SessionId" text NOT NULL,
        "FileName" text NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "FileHash" text NOT NULL,
        "TotalChunks" integer NOT NULL,
        "UploadedChunks" boolean[] NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ClientIpAddress" text NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_ChunkUploadSessions" PRIMARY KEY ("SessionId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251027152153_AddChunks') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251027152153_AddChunks', '10.0.1');
    END IF;
END $$;
COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Scans" ADD "ApiKeyId" uuid;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Scans" ADD "FileHash" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Scans" ADD "UserId" uuid;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "AnalyzerVersion" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "ApiKeyId" uuid;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "AssemblyCompany" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "AssemblyCopyright" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "AssemblyGuid" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "AssemblyProduct" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "AssemblyTitle" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD "UserId" uuid;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "Endpoints" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Path" character varying(500) NOT NULL,
        CONSTRAINT "PK_Endpoints" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "Users" (
        "Id" uuid NOT NULL,
        "Email" character varying(255),
        "Tier" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "IsAdmin" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "ApiKeys" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "KeyHash" character varying(255) NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Prefix" character varying(20) NOT NULL,
        "LastSixChars" character varying(10) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone,
        "LastUsedAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "Scopes" integer NOT NULL,
        "IpWhitelist" character varying(1000),
        CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ApiKeys_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "Badges" (
        "Id" character varying(50) NOT NULL,
        "UserId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Description" character varying(500),
        "LinkedFileHash" text NOT NULL,
        "UpdateSalt" character varying(64),
        "UpdateToken" character varying(64),
        "RequireTokenForUpdate" boolean NOT NULL,
        "TrackedAssemblyCompany" text,
        "TrackedAssemblyProduct" text,
        "TrackedAssemblyGuid" text,
        "TrackedFileName" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "VersionUpdateCount" integer NOT NULL,
        CONSTRAINT "PK_Badges" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Badges_Files_LinkedFileHash" FOREIGN KEY ("LinkedFileHash") REFERENCES "Files" ("Hash") ON DELETE CASCADE,
        CONSTRAINT "FK_Badges_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Token" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "IsRevoked" boolean NOT NULL,
        "RevokedAt" timestamp with time zone,
        "CreatedByIp" character varying(50),
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "UserIdentities" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "Provider" integer NOT NULL,
        "ProviderUserId" character varying(100) NOT NULL,
        "ProviderUsername" character varying(100),
        "AvatarUrl" character varying(255),
        "ConnectedAt" timestamp with time zone NOT NULL DEFAULT (TIMEZONE('UTC', NOW())),
        "LastAuthenticatedAt" timestamp with time zone,
        CONSTRAINT "PK_UserIdentities" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserIdentities_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE TABLE IF NOT EXISTS "ApiKeyUsages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ApiKeyId" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "EndpointId" integer NOT NULL,
        "Method" integer NOT NULL,
        "StatusCode" integer NOT NULL,
        "ResponseTimeMs" integer NOT NULL,
        "RequestedAt" timestamp with time zone NOT NULL,
        "ClientIpAddress" character varying(50),
        CONSTRAINT "PK_ApiKeyUsages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ApiKeyUsages_ApiKeys_ApiKeyId" FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ApiKeyUsages_Endpoints_EndpointId" FOREIGN KEY ("EndpointId") REFERENCES "Endpoints" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ApiKeyUsages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Scans_ApiKeyId" ON "Scans" ("ApiKeyId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Scans_ScanDate" ON "Scans" ("ScanDate");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Scans_UserId" ON "Scans" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Files_AddDateTime" ON "Files" ("AddDateTime");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Files_ApiKeyId" ON "Files" ("ApiKeyId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Files_UserId" ON "Files" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ChunkUploadSessions_ClientIpAddress" ON "ChunkUploadSessions" ("ClientIpAddress");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ChunkUploadSessions_ExpiresAt" ON "ChunkUploadSessions" ("ExpiresAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeys_KeyHash" ON "ApiKeys" ("KeyHash");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeys_UserId" ON "ApiKeys" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeyUsages_ApiKeyId" ON "ApiKeyUsages" ("ApiKeyId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeyUsages_EndpointId" ON "ApiKeyUsages" ("EndpointId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeyUsages_RequestedAt" ON "ApiKeyUsages" ("RequestedAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeyUsages_UserId" ON "ApiKeyUsages" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_ApiKeyUsages_UserId_RequestedAt" ON "ApiKeyUsages" ("UserId", "RequestedAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Badges_LinkedFileHash" ON "Badges" ("LinkedFileHash");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Badges_UpdatedAt" ON "Badges" ("UpdatedAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_Badges_UserId" ON "Badges" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE UNIQUE INDEX "IX_Endpoints_Path" ON "Endpoints" ("Path");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_RefreshTokens_ExpiresAt" ON "RefreshTokens" ("ExpiresAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_RefreshTokens_UserId_IsRevoked_ExpiresAt" ON "RefreshTokens" ("UserId", "IsRevoked", "ExpiresAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_UserIdentities_Provider" ON "UserIdentities" ("Provider");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE UNIQUE INDEX "IX_UserIdentities_Provider_ProviderUserId" ON "UserIdentities" ("Provider", "ProviderUserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE INDEX "IX_UserIdentities_UserId" ON "UserIdentities" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD CONSTRAINT "FK_Files_ApiKeys_ApiKeyId" FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("Id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Files" ADD CONSTRAINT "FK_Files_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Scans" ADD CONSTRAINT "FK_Scans_ApiKeys_ApiKeyId" FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("Id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    ALTER TABLE "Scans" ADD CONSTRAINT "FK_Scans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251130132417_Dotnet10') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251130132417_Dotnet10', '10.0.1');
    END IF;
END $$;
COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    ALTER TABLE "ApiKeyUsages" ADD "ClientTag" character varying(50);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE TABLE IF NOT EXISTS "LoaderReleases" (
        "Id" uuid NOT NULL,
        "Framework" character varying(50) NOT NULL,
        "Configuration" character varying(50) NOT NULL,
        "Version" character varying(50) NOT NULL,
        "PackedVersion" bigint NOT NULL,
        "DownloadUrl" character varying(512),
        "Sha256" character varying(128),
        "SourceRepo" character varying(100),
        "AssetName" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsLatest" boolean NOT NULL,
        "Content" bytea,
        "ContentHash" character varying(128),
        CONSTRAINT "PK_LoaderReleases" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE TABLE IF NOT EXISTS "PluginInstallerReleases" (
        "Id" uuid NOT NULL,
        "Framework" character varying(50) NOT NULL,
        "Version" character varying(50) NOT NULL,
        "PackedVersion" bigint NOT NULL,
        "DownloadUrl" character varying(512),
        "Sha256" character varying(128),
        "SourceRepo" character varying(100),
        "AssetName" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsLatest" boolean NOT NULL,
        "Content" bytea,
        "ContentHash" character varying(128),
        CONSTRAINT "PK_PluginInstallerReleases" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE TABLE IF NOT EXISTS "PluginReleases" (
        "Id" uuid NOT NULL,
        "Framework" character varying(50) NOT NULL,
        "Version" character varying(50) NOT NULL,
        "PackedVersion" bigint NOT NULL,
        "DownloadUrl" character varying(512),
        "Sha256" character varying(128),
        "SourceRepo" character varying(100),
        "AssetName" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsLatest" boolean NOT NULL,
        "Content" bytea,
        "ContentHash" character varying(128),
        CONSTRAINT "PK_PluginReleases" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE INDEX "IX_LoaderReleases_Framework_Configuration_IsLatest" ON "LoaderReleases" ("Framework", "Configuration", "IsLatest");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE UNIQUE INDEX "IX_LoaderReleases_Framework_Configuration_Version" ON "LoaderReleases" ("Framework", "Configuration", "Version");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE INDEX "IX_PluginInstallerReleases_Framework_IsLatest" ON "PluginInstallerReleases" ("Framework", "IsLatest");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE UNIQUE INDEX "IX_PluginInstallerReleases_Framework_Version" ON "PluginInstallerReleases" ("Framework", "Version");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE INDEX "IX_PluginReleases_Framework_IsLatest" ON "PluginReleases" ("Framework", "IsLatest");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    CREATE UNIQUE INDEX "IX_PluginReleases_Framework_Version" ON "PluginReleases" ("Framework", "Version");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251214095351_PluginsAndLoaders') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251214095351_PluginsAndLoaders', '10.0.1');
    END IF;
END $$;
COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260102121747_MakeBadgeLinkedFileOptional') THEN
    ALTER TABLE "Badges" DROP CONSTRAINT "FK_Badges_Files_LinkedFileHash";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260102121747_MakeBadgeLinkedFileOptional') THEN
    ALTER TABLE "Badges" ALTER COLUMN "LinkedFileHash" DROP NOT NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260102121747_MakeBadgeLinkedFileOptional') THEN
    ALTER TABLE "Badges" ADD CONSTRAINT "FK_Badges_Files_LinkedFileHash" FOREIGN KEY ("LinkedFileHash") REFERENCES "Files" ("Hash");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260102121747_MakeBadgeLinkedFileOptional') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260102121747_MakeBadgeLinkedFileOptional', '10.0.1');
    END IF;
END $$;
COMMIT;

START TRANSACTION;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" DROP CONSTRAINT "FK_Files_Users_UserId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Users" DROP COLUMN "IsAdmin";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Users" ADD "Permissions" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "CurrentVerdict" integer;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "Features" jsonb;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "IsTakenDown" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "PublicAdminMessage" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "TakedownReason" text;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "TakenDownAt" timestamp with time zone;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD "TakenDownByUserId" uuid;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE TABLE IF NOT EXISTS "AnalysisJobs" (
        "Id" uuid NOT NULL,
        "Status" integer NOT NULL,
        "FileName" text NOT NULL,
        "FileHash" text NOT NULL,
        "FileSizeBytes" bigint NOT NULL,
        "HangfireJobId" text,
        "UserId" uuid,
        "ApiKeyId" uuid,
        "ClientIpAddress" text,
        "ForceAnalyze" boolean NOT NULL,
        "BadgeToken" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "StartedAt" timestamp with time zone,
        "CompletedAt" timestamp with time zone,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "ResultJson" text,
        "ErrorMessage" text,
        "RetryCount" integer NOT NULL,
        "TempFilePath" text,
        "TempFileCleanedUp" boolean NOT NULL,
        CONSTRAINT "PK_AnalysisJobs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AnalysisJobs_ApiKeys_ApiKeyId" FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("Id"),
        CONSTRAINT "FK_AnalysisJobs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE TABLE IF NOT EXISTS "FileAdminReviews" (
        "Id" uuid NOT NULL,
        "FileHash" text NOT NULL,
        "ReviewerId" uuid NOT NULL,
        "Verdict" integer NOT NULL,
        "PublicMessage" text,
        "InternalNotes" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_FileAdminReviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FileAdminReviews_Files_FileHash" FOREIGN KEY ("FileHash") REFERENCES "Files" ("Hash") ON DELETE CASCADE,
        CONSTRAINT "FK_FileAdminReviews_Users_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_Files_CurrentVerdict" ON "Files" ("CurrentVerdict");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_Files_IsTakenDown" ON "Files" ("IsTakenDown");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_Files_TakenDownAt" ON "Files" ("TakenDownAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_Files_TakenDownByUserId" ON "Files" ("TakenDownByUserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_AnalysisJobs_ApiKeyId" ON "AnalysisJobs" ("ApiKeyId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_AnalysisJobs_CreatedAt" ON "AnalysisJobs" ("CreatedAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_AnalysisJobs_ExpiresAt" ON "AnalysisJobs" ("ExpiresAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_AnalysisJobs_FileHash" ON "AnalysisJobs" ("FileHash");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_AnalysisJobs_Status" ON "AnalysisJobs" ("Status");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_AnalysisJobs_UserId" ON "AnalysisJobs" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_FileAdminReviews_CreatedAt" ON "FileAdminReviews" ("CreatedAt");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_FileAdminReviews_FileHash" ON "FileAdminReviews" ("FileHash");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_FileAdminReviews_ReviewerId" ON "FileAdminReviews" ("ReviewerId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    CREATE INDEX "IX_FileAdminReviews_Verdict" ON "FileAdminReviews" ("Verdict");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD CONSTRAINT "FK_Files_Users_TakenDownByUserId" FOREIGN KEY ("TakenDownByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    ALTER TABLE "Files" ADD CONSTRAINT "FK_Files_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260107113506_RevampPermissionsAndQueuedAnalysis') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260107113506_RevampPermissionsAndQueuedAnalysis', '10.0.1');
    END IF;
END $$;
COMMIT;

